---
version: "3.1"
# version: "2.1"

services:

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - 9200:9200
    expose:
      - "9200"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9200"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - 5601:5601
    networks:
      - esnet
